version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/app/client"
    schedule:
      interval: "monthly"
      day: "wednesday"
      time: "06:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/app/server"
    schedule:
      interval: "monthly"
      day: "wednesday"
      time: "06:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directories:
      - "/app/client"
      - "/app/server"
    schedule:
      interval: "monthly"
      day: "wednesday"
      time: "06:00"
      timezone: "Europe/Rome"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "wednesday"
      time: "06:00"
      timezone: "Europe/Rome"
